apiVersion: v2
name: bindy-crds
description: CustomResourceDefinitions for the Bindy BIND9 Kubernetes Operator
type: application
version: 0.5.2
appVersion: "v0.5.2"
keywords:
  - dns
  - bind9
  - crds
home: https://github.com/firestoned/bindy
sources:
  - https://github.com/firestoned/bindy
  - https://github.com/Hobart2967/bindy-charts
