apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bindy.fullname" . }}-role
  labels:
    {{- include "bindy.labels" . | nindent 4 }}
  annotations:
    # Trivy suppressions — see upstream justifications in firestoned/bindy
    trivy.aquasecurity.com/ignore: KSV-0041,KSV-0056
rules:
- apiGroups:
  - bindy.firestoned.io
  resources:
  - bind9instances
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - bindy.firestoned.io
  resources:
  - bind9instances/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - bindy.firestoned.io
  resources:
  - bind9clusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - bindy.firestoned.io
  resources:
  - bind9clusters/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - bindy.firestoned.io
  resources:
  - clusterbind9providers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - bindy.firestoned.io
  resources:
  - clusterbind9providers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - bindy.firestoned.io
  resources:
  - dnszones
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - bindy.firestoned.io
  resources:
  - dnszones/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - bindy.firestoned.io
  resources:
  - arecords
  - aaaarecords
  - txtrecords
  - cnamerecords
  - mxrecords
  - nsrecords
  - srvrecords
  - caarecords
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - bindy.firestoned.io
  resources:
  - arecords/status
  - aaaarecords/status
  - txtrecords/status
  - cnamerecords/status
  - mxrecords/status
  - nsrecords/status
  - srvrecords/status
  - caarecords/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - patch
